#!/usr/bin/sh

text="#include <iostream>\n\
#include <string>\n\
#include <stdio.h>\n\
#include <cstring>\n\
#include <unistd.h>\n\
#include <cstdlib>\n\
using namespace std;\n\
\n\
int main() {\n\
\n\
\n\
\treturn 0;\n\
}"

echo -e $text >$1
